### PR TITLE
Parse json output for `mise config ls`

### PR DESCRIPTION
**Pull request by dpassen**

### CODE REVIEW

**Comment by liuyinz** [comment]
Actually we only need config files, `mise ls --verbose` is enough.

**Comment by dpassen** [comment]
`mise ls` seems to be about tools, not configuration files. At least to my eyes.

**Comment by dpassen** [comment]
This looks to have broken again in the latest mise. The regex approach seems to regularly break. I really think we should use the `mise config ls --json` approach.

**Comment by dpassen** [comment]
The last time we updated the regex, the output looked like:
```sh
$ mise config ls --verbose
DEBUG mise::cli ARGS: /usr/local/bin/mise config ls --verbose
DEBUG xx::file ls: "/Users/dpassen/.local/share/mise/plugins"
DEBUG xx::file ls: "/Users/dpassen/.local/share/mise/plugins"
DEBUG mise::config config: ~/PATH-TO-PROJECT/.mise.local.toml
DEBUG mise::config config: ~/PATH-TO-PROJECT/.mise.toml
DEBUG mise::config config: ~/.config/mise/config.toml
Path                                Plugins                  
~/PATH-TO-PROJECT/.mise.local.toml (none)                   
~/PATH-TO-PROJECT/.mise.toml       (none)                   
~/.config/mise/config.toml         java, node, python, usage
```

Now, it looks like:
```sh
$ mise config ls --verbose
DEBUG ARGS: /usr/local/bin/mise config ls --verbose
DEBUG vfox_plugin: "/Users/dpassen/.local/share/mise/plugins/rust"
DEBUG vfox_plugin: "/Users/dpassen/.local/share/mise/plugins/usage"
DEBUG config: ~/PATH-TO-PROJECT/.mise.local.toml
DEBUG config: ~/PATH-TO-PROJECT/.mise.toml
DEBUG config: ~/.config/mise/config.toml
Path                                Plugins                  
~/PATH-TO-PROJECT/.mise.local.toml (none)                   
~/PATH-TO-PROJECT/.mise.toml       (none)                   
~/.config/mise/config.toml         java, node, python, usage
```

**Comment by liuyinz** [comment]
You are right, I will make it.

**Comment by dpassen** [comment]
Rebased this approach

**Comment by liuyinz** [comment]
@dpassen I have commit the new approach to detect configs, please test it.

**Comment by dpassen** [comment]
Working for me!

**Pull request closed without merging**
